export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const SET_TODO = "SET_TODO"
export const SET_TODOLOADING = "SET_TODOLOADING"
export const DELETE_TODOLOADING = "DELETE_TODOLOADING"


export const ADD_USER = "ADD_USER"
export const SET_USERLOADING = "SET_USERLOADING"
export const DELETE_USERLOADING = "DELET_USERLOADING"
export const DELETE_USER = "DELETE_USER"

export const CHANGE_THEME = "CHANGE_THEME"
